//
// File generated by /app/cern/root_v5.34.38/bin/rootcint at Tue Feb 11 16:58:43 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCFitterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCFitterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void BCFitter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCFitter_Dictionary();
   static void delete_BCFitter(void *p);
   static void deleteArray_BCFitter(void *p);
   static void destruct_BCFitter(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::BCFitter*)
   {
      ::BCFitter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCFitter),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCFitter", "./BCFitter.h", 28,
                  typeid(::BCFitter), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &BCFitter_Dictionary, isa_proxy, 0,
                  sizeof(::BCFitter) );
      instance.SetDelete(&delete_BCFitter);
      instance.SetDeleteArray(&deleteArray_BCFitter);
      instance.SetDestructor(&destruct_BCFitter);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::BCFitter*)
   {
      return GenerateInitInstanceLocal((::BCFitter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCFitter*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCFitter_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::BCFitter*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_BCFitter(void *p) {
      delete ((::BCFitter*)p);
   }
   static void deleteArray_BCFitter(void *p) {
      delete [] ((::BCFitter*)p);
   }
   static void destruct_BCFitter(void *p) {
      typedef ::BCFitter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::BCFitter

/********************************************************
* BCFitterDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCFitterDict();

extern "C" void G__set_cpp_environmentBCFitterDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BCFitter.h");
  G__cpp_reset_tagtableBCFitterDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCFitterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCFitter */
static int G__BCFitterDict_244_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCFitter*) G__getstructoffset())->GetErrorBand());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const BCFitter*) G__getstructoffset())->GetErrorBandXY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) ((const BCFitter*) G__getstructoffset())->GetErrorBandXY_yellow((double) G__double(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((const BCFitter*) G__getstructoffset())->GetErrorBandXY_yellow((double) G__double(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 85, (long) ((const BCFitter*) G__getstructoffset())->GetErrorBandXY_yellow());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<double>* pobj;
         const vector<double> xobj = ((const BCFitter*) G__getstructoffset())->GetErrorBand((double) G__double(libp->para[0]));
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const BCFitter*) G__getstructoffset())->GetErrorBandGraph((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCFitter*) G__getstructoffset())->GetFitFunctionGraph(*(vector<double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCFitter*) G__getstructoffset())->GetFitFunctionGraph());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 85, (long) ((BCFitter*) G__getstructoffset())->GetFitFunctionGraph(*(vector<double>*) libp->para[0].ref, (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (int) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) ((BCFitter*) G__getstructoffset())->GetFitFunctionGraph(*(vector<double>*) libp->para[0].ref, (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->FixDataAxis((unsigned int) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const BCFitter*) G__getstructoffset())->GetFixedDataAxis((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCFitter*) G__getstructoffset())->SetFillErrorBand((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCFitter*) G__getstructoffset())->SetFillErrorBand();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->SetErrorBandHisto((TH2D*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->UnsetFillErrorBand();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->SetFitFunctionIndexX((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->SetFitFunctionIndexY((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->SetFitFunctionIndices((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->SetErrorBandContinuous((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCFitter*) G__getstructoffset())->FitFunction(*(vector<double>*) libp->para[0].ref, *(vector<double>*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCFitter*) G__getstructoffset())->ReadErrorBandFromFile((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCFitter*) G__getstructoffset())->Fit());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((BCFitter*) G__getstructoffset())->DrawFit((const char*) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((BCFitter*) G__getstructoffset())->DrawFit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCFitterDict_244_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCFitter*) G__getstructoffset())->FillErrorBand();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCFitter G__TBCFitter;
static int G__BCFitterDict_244_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCFitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCFitter*) (soff+(sizeof(BCFitter)*i)))->~G__TBCFitter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCFitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCFitter*) (soff))->~G__TBCFitter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BCFitterDict_244_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCFitter* dest = (BCFitter*) G__getstructoffset();
   *dest = *(BCFitter*) libp->para[0].ref;
   const BCFitter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCFitter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCFitterDict {
 public:
  G__Sizep2memfuncBCFitterDict(): p(&G__Sizep2memfuncBCFitterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCFitterDict::*p)();
};

size_t G__get_sizep2memfuncBCFitterDict()
{
  G__Sizep2memfuncBCFitterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCFitterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BCFitterDictLN_BCFitter))) {
     BCFitter *G__Lderived;
     G__Lderived=(BCFitter*)0x1000;
     {
       BCModel *G__Lpbase=(BCModel*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCFitterDictLN_BCFitter),G__get_linked_tagnum(&G__BCFitterDictLN_BCModel),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       BCIntegrate *G__Lpbase=(BCIntegrate*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCFitterDictLN_BCFitter),G__get_linked_tagnum(&G__BCFitterDictLN_BCIntegrate),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       BCEngineMCMC *G__Lpbase=(BCEngineMCMC*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCFitterDictLN_BCFitter),G__get_linked_tagnum(&G__BCFitterDictLN_BCEngineMCMC),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCFitterDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCParameter*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<unsigned>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TTree*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MCMCThreadLocalStorage>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCEngineMCMC::MCMCThreadLocalStorage>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2D*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCH1D*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCH2D*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TNamed*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCModel*>",117,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCFitter */
static void G__setup_memvarBCFitter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCFitterDictLN_BCFitter));
   { BCFitter *p; p=(BCFitter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCFitterDictLN_TGraph),-1,-1,4,"fErrorBand=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fFlagFillErrorBand=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fFitFunctionIndexX=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fFitFunctionIndexY=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fErrorBandContinuous=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fErrorBandX=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fErrorBandNbinsX=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fErrorBandNbinsY=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCFitterDictLN_TH2D),-1,-1,2,"fErrorBandXY=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCFitterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCFitter(void) {
   /* BCFitter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCFitterDictLN_BCFitter));
   G__memfunc_setup("GetErrorBand",1183,G__BCFitterDict_244_0_3, 85, G__get_linked_tagnum(&G__BCFitterDictLN_TGraph), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetErrorBandXY",1360,G__BCFitterDict_244_0_4, 85, G__get_linked_tagnum(&G__BCFitterDictLN_TH2D), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetErrorBandXY_yellow",2123,G__BCFitterDict_244_0_5, 85, G__get_linked_tagnum(&G__BCFitterDictLN_TH2D), -1, 0, 2, 1, 1, 8, 
"d - - 0 '.68' level i - - 0 '0' nsmooth", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetErrorBand",1183,G__BCFitterDict_244_0_6, 117, G__get_linked_tagnum(&G__BCFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 1, 1, 1, 8, "d - - 0 - level", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetErrorBandGraph",1681,G__BCFitterDict_244_0_7, 85, G__get_linked_tagnum(&G__BCFitterDictLN_TGraph), -1, 0, 2, 1, 1, 8, 
"d - - 0 - level1 d - - 0 - level2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFitFunctionGraph",1915,G__BCFitterDict_244_0_8, 85, G__get_linked_tagnum(&G__BCFitterDictLN_TGraph), -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFitFunctionGraph",1915,G__BCFitterDict_244_0_9, 85, G__get_linked_tagnum(&G__BCFitterDictLN_TGraph), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFitFunctionGraph",1915,G__BCFitterDict_244_0_10, 85, G__get_linked_tagnum(&G__BCFitterDictLN_TGraph), -1, 0, 4, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters d - - 0 - xmin "
"d - - 0 - xmax i - - 0 '1000' n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FixDataAxis",1078,G__BCFitterDict_244_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - - 0 - index g - - 0 - fixed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFixedDataAxis",1567,G__BCFitterDict_244_0_12, 103, -1, -1, 0, 1, 1, 1, 8, "h - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFillErrorBand",1586,G__BCFitterDict_244_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetErrorBandHisto",1714,G__BCFitterDict_244_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH2D' - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnsetFillErrorBand",1813,G__BCFitterDict_244_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFitFunctionIndexX",2021,G__BCFitterDict_244_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFitFunctionIndexY",2022,G__BCFitterDict_244_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFitFunctionIndices",2132,G__BCFitterDict_244_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - indexx i - - 0 - indexy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetErrorBandContinuous",2274,G__BCFitterDict_244_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FitFunction",1129,G__BCFitterDict_244_0_20, 100, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<double>' 11 - - u 'vector<double,allocator<double> >' 'vector<double>' 11 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ReadErrorBandFromFile",2063,G__BCFitterDict_244_0_21, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - file", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Fit",291,G__BCFitterDict_244_0_22, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("DrawFit",689,G__BCFitterDict_244_0_23, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - options g - - 0 'false' flaglegend", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("MCMCIterationInterface",2144,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MarginalizePreprocess",2201,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MarginalizePostprocess",2328,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FillErrorBand",1286,G__BCFitterDict_244_0_27, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCFitter", 881, G__BCFitterDict_244_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BCFitterDict_244_0_29, (int) ('u'), G__get_linked_tagnum(&G__BCFitterDictLN_BCFitter), -1, 1, 1, 1, 1, 0, "u 'BCFitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCFitterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCFitterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCFitterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCFitterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR = { "vector<BCParameter*,allocator<BCParameter*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCParameter*,allocator<BCParameter*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_TH2D = { "TH2D" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_BCEngineMCMC = { "BCEngineMCMC" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR = { "vector<TTree*,allocator<TTree*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TTree*,allocator<TTree*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR = { "vector<BCEngineMCMC::MCMCThreadLocalStorage,allocator<BCEngineMCMC::MCMCThreadLocalStorage> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCEngineMCMC::MCMCThreadLocalStorage,allocator<BCEngineMCMC::MCMCThreadLocalStorage> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR = { "vector<TH2D*,allocator<TH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2D*,allocator<TH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_BCIntegrate = { "BCIntegrate" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR = { "vector<BCH1D*,allocator<BCH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCH1D*,allocator<BCH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR = { "vector<BCH2D*,allocator<BCH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCH2D*,allocator<BCH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_BCModel = { "BCModel" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR = { "vector<TNamed*,allocator<TNamed*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TNamed*,allocator<TNamed*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR = { "vector<BCModel*,allocator<BCModel*> >" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCModel*,allocator<BCModel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCFitterDictLN_BCFitter = { "BCFitter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCFitterDict() {
  G__BCFitterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_TH2D.tagnum = -1 ;
  G__BCFitterDictLN_BCEngineMCMC.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_BCIntegrate.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_TGraph.tagnum = -1 ;
  G__BCFitterDictLN_BCModel.tagnum = -1 ;
  G__BCFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR.tagnum = -1 ;
  G__BCFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCFitterDictLN_BCFitter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCFitterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_TH2D);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_BCEngineMCMC);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_BCIntegrate);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_BCModel);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCFitterDictLN_BCFitter),sizeof(BCFitter),-1,34051,(char*)NULL,G__setup_memvarBCFitter,G__setup_memfuncBCFitter);
}
extern "C" void G__cpp_setupBCFitterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCFitterDict()");
  G__set_cpp_environmentBCFitterDict();
  G__cpp_setup_tagtableBCFitterDict();

  G__cpp_setup_inheritanceBCFitterDict();

  G__cpp_setup_typetableBCFitterDict();

  G__cpp_setup_memvarBCFitterDict();

  G__cpp_setup_memfuncBCFitterDict();
  G__cpp_setup_globalBCFitterDict();
  G__cpp_setup_funcBCFitterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCFitterDict();
  return;
}
class G__cpp_setup_initBCFitterDict {
  public:
    G__cpp_setup_initBCFitterDict() { G__add_setup_func("BCFitterDict",(G__incsetup)(&G__cpp_setupBCFitterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCFitterDict() { G__remove_setup_func("BCFitterDict"); }
};
G__cpp_setup_initBCFitterDict G__cpp_setup_initializerBCFitterDict;

