/********************************************************************
* BCFitterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCFitterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCFitterDict();
extern void G__cpp_setup_inheritanceBCFitterDict();
extern void G__cpp_setup_typetableBCFitterDict();
extern void G__cpp_setup_memvarBCFitterDict();
extern void G__cpp_setup_globalBCFitterDict();
extern void G__cpp_setup_memfuncBCFitterDict();
extern void G__cpp_setup_funcBCFitterDict();
extern void G__set_cpp_environmentBCFitterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BCFitter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCFitterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_TH2D;
extern G__linked_taginfo G__BCFitterDictLN_BCEngineMCMC;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_BCIntegrate;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_TGraph;
extern G__linked_taginfo G__BCFitterDictLN_BCModel;
extern G__linked_taginfo G__BCFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR;
extern G__linked_taginfo G__BCFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCFitterDictLN_BCFitter;

/* STUB derived class for protected member access */
