#238U chain

#/xe/generateCE  0
#/tracking/verbose 0
#/run/verbose 0
#/control/verbose 0
#/xe/gun/verbose 0

/Xe/saveHits 1
/Xe/printModulo 1000


/xe/gun/particle ion
/xe/gun/ion 92 238 0 0
/grdm/nucleusLimits 234 238 92 92

/xe/gun/energy 0 keV

/xe/gun/type Volume
/xe/gun/shape Cylinder
/xe/gun/radius 70 mm
/xe/gun/halfz 60 mm
/xe/gun/center 0 0 100 mm
/xe/gun/confine crystal_phys active_phys

/run/beamOn 10000