/********************************************************************
* BCMVCMeasurementDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCMVCMeasurementDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCMVCMeasurementDict();
extern void G__cpp_setup_inheritanceBCMVCMeasurementDict();
extern void G__cpp_setup_typetableBCMVCMeasurementDict();
extern void G__cpp_setup_memvarBCMVCMeasurementDict();
extern void G__cpp_setup_globalBCMVCMeasurementDict();
extern void G__cpp_setup_memfuncBCMVCMeasurementDict();
extern void G__cpp_setup_funcBCMVCMeasurementDict();
extern void G__set_cpp_environmentBCMVCMeasurementDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BCMVCMeasurement.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCMVCMeasurementDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__BCMVCMeasurementDictLN_string;
extern G__linked_taginfo G__BCMVCMeasurementDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCMVCMeasurementDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMVCMeasurementDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCMVCMeasurementDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMVCMeasurementDictLN_BCMVCMeasurement;

/* STUB derived class for protected member access */
