/********************************************************************
* BCMVCObservableDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCMVCObservableDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCMVCObservableDict();
extern void G__cpp_setup_inheritanceBCMVCObservableDict();
extern void G__cpp_setup_typetableBCMVCObservableDict();
extern void G__cpp_setup_memvarBCMVCObservableDict();
extern void G__cpp_setup_globalBCMVCObservableDict();
extern void G__cpp_setup_memfuncBCMVCObservableDict();
extern void G__cpp_setup_funcBCMVCObservableDict();
extern void G__set_cpp_environmentBCMVCObservableDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BCMVCObservable.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCMVCObservableDictLN_string;
extern G__linked_taginfo G__BCMVCObservableDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCMVCObservableDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMVCObservableDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCMVCObservableDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMVCObservableDictLN_BCMVCObservable;

/* STUB derived class for protected member access */
