//
// File generated by /app/cern/root_v5.34.38/bin/rootcint at Tue Feb 11 16:59:53 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCMVCPhysicsModelDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCMVCPhysicsModelDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void BCMVCPhysicsModel_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCMVCPhysicsModel_Dictionary();
   static void *new_BCMVCPhysicsModel(void *p = 0);
   static void *newArray_BCMVCPhysicsModel(Long_t size, void *p);
   static void delete_BCMVCPhysicsModel(void *p);
   static void deleteArray_BCMVCPhysicsModel(void *p);
   static void destruct_BCMVCPhysicsModel(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::BCMVCPhysicsModel*)
   {
      ::BCMVCPhysicsModel *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCMVCPhysicsModel),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCMVCPhysicsModel", "./BCMVCPhysicsModel.h", 18,
                  typeid(::BCMVCPhysicsModel), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &BCMVCPhysicsModel_Dictionary, isa_proxy, 0,
                  sizeof(::BCMVCPhysicsModel) );
      instance.SetNew(&new_BCMVCPhysicsModel);
      instance.SetNewArray(&newArray_BCMVCPhysicsModel);
      instance.SetDelete(&delete_BCMVCPhysicsModel);
      instance.SetDeleteArray(&deleteArray_BCMVCPhysicsModel);
      instance.SetDestructor(&destruct_BCMVCPhysicsModel);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::BCMVCPhysicsModel*)
   {
      return GenerateInitInstanceLocal((::BCMVCPhysicsModel*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCMVCPhysicsModel*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCMVCPhysicsModel_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::BCMVCPhysicsModel*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_BCMVCPhysicsModel(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCMVCPhysicsModel : new ::BCMVCPhysicsModel;
   }
   static void *newArray_BCMVCPhysicsModel(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCMVCPhysicsModel[nElements] : new ::BCMVCPhysicsModel[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCMVCPhysicsModel(void *p) {
      delete ((::BCMVCPhysicsModel*)p);
   }
   static void deleteArray_BCMVCPhysicsModel(void *p) {
      delete [] ((::BCMVCPhysicsModel*)p);
   }
   static void destruct_BCMVCPhysicsModel(void *p) {
      typedef ::BCMVCPhysicsModel current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::BCMVCPhysicsModel

/********************************************************
* BCMVCPhysicsModelDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCMVCPhysicsModelDict();

extern "C" void G__set_cpp_environmentBCMVCPhysicsModelDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BCMVCPhysicsModel.h");
  G__cpp_reset_tagtableBCMVCPhysicsModelDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCMVCPhysicsModelDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCMVCPhysicsModel */
static int G__BCMVCPhysicsModelDict_355_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCMVCPhysicsModel* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCMVCPhysicsModel[n];
     } else {
       p = new((void*) gvp) BCMVCPhysicsModel[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCMVCPhysicsModel;
     } else {
       p = new((void*) gvp) BCMVCPhysicsModel;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCPhysicsModelDict_355_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCPhysicsModel*) G__getstructoffset())->AddObservable(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCPhysicsModelDict_355_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCMVCPhysicsModel*) G__getstructoffset())->CalculateObservable((int) G__int(libp->para[0]), *(vector<double>*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BCMVCPhysicsModelDict_355_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BCMVCPhysicsModel* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BCMVCPhysicsModel(*(BCMVCPhysicsModel*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCMVCPhysicsModel G__TBCMVCPhysicsModel;
static int G__BCMVCPhysicsModelDict_355_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCMVCPhysicsModel*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCMVCPhysicsModel*) (soff+(sizeof(BCMVCPhysicsModel)*i)))->~G__TBCMVCPhysicsModel();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCMVCPhysicsModel*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCMVCPhysicsModel*) (soff))->~G__TBCMVCPhysicsModel();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BCMVCPhysicsModelDict_355_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCMVCPhysicsModel* dest = (BCMVCPhysicsModel*) G__getstructoffset();
   *dest = *(BCMVCPhysicsModel*) libp->para[0].ref;
   const BCMVCPhysicsModel& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCMVCPhysicsModel */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCMVCPhysicsModelDict {
 public:
  G__Sizep2memfuncBCMVCPhysicsModelDict(): p(&G__Sizep2memfuncBCMVCPhysicsModelDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCMVCPhysicsModelDict::*p)();
};

size_t G__get_sizep2memfuncBCMVCPhysicsModelDict()
{
  G__Sizep2memfuncBCMVCPhysicsModelDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCMVCPhysicsModelDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel))) {
     BCMVCPhysicsModel *G__Lderived;
     G__Lderived=(BCMVCPhysicsModel*)0x1000;
     {
       BCMVCombination *G__Lpbase=(BCMVCombination*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel),G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCombination),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       BCModel *G__Lpbase=(BCModel*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel),G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCModel),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       BCIntegrate *G__Lpbase=(BCIntegrate*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel),G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCIntegrate),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       BCEngineMCMC *G__Lpbase=(BCEngineMCMC*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel),G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCEngineMCMC),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCMVCPhysicsModelDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCParameter*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<unsigned>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TTree*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MCMCThreadLocalStorage>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCEngineMCMC::MCMCThreadLocalStorage>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2D*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCH1D*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCH2D*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TNamed*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCModel*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCUncertainty*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCMeasurement*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVectorD>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVectorT<double> >",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixD>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixT<double> >",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<NuisanceParameter>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCombination::NuisanceParameter>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCObservable*>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCMVCPhysicsModel */
static void G__setup_memvarBCMVCPhysicsModel(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel));
   { BCMVCPhysicsModel *p; p=(BCMVCPhysicsModel*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCMVCPhysicsModelDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCMVCPhysicsModel(void) {
   /* BCMVCPhysicsModel */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel));
   G__memfunc_setup("BCMVCPhysicsModel",1599,G__BCMVCPhysicsModelDict_355_0_1, 105, G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddObservable",1294,G__BCMVCPhysicsModelDict_355_0_2, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - name d - - 0 - min "
"d - - 0 - max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateObservable",1939,G__BCMVCPhysicsModelDict_355_0_3, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - index u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LogLikelihood",1318,(G__InterfaceMethod) NULL,100, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("BCMVCPhysicsModel", 1599, G__BCMVCPhysicsModelDict_355_0_5, (int) ('i'), G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel), -1, 0, 1, 1, 1, 0, "u 'BCMVCPhysicsModel' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCMVCPhysicsModel", 1725, G__BCMVCPhysicsModelDict_355_0_6, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BCMVCPhysicsModelDict_355_0_7, (int) ('u'), G__get_linked_tagnum(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel), -1, 1, 1, 1, 1, 0, "u 'BCMVCPhysicsModel' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCMVCPhysicsModelDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCMVCPhysicsModelDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCMVCPhysicsModelDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR = { "vector<BCParameter*,allocator<BCParameter*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCParameter*,allocator<BCParameter*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_BCEngineMCMC = { "BCEngineMCMC" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR = { "vector<TTree*,allocator<TTree*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TTree*,allocator<TTree*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR = { "vector<BCEngineMCMC::MCMCThreadLocalStorage,allocator<BCEngineMCMC::MCMCThreadLocalStorage> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCEngineMCMC::MCMCThreadLocalStorage,allocator<BCEngineMCMC::MCMCThreadLocalStorage> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR = { "vector<TH2D*,allocator<TH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2D*,allocator<TH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_BCIntegrate = { "BCIntegrate" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR = { "vector<BCH1D*,allocator<BCH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCH1D*,allocator<BCH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR = { "vector<BCH2D*,allocator<BCH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCH2D*,allocator<BCH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_BCModel = { "BCModel" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR = { "vector<TNamed*,allocator<TNamed*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TNamed*,allocator<TNamed*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR = { "vector<BCModel*,allocator<BCModel*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCModel*,allocator<BCModel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_BCMVCombination = { "BCMVCombination" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR = { "vector<BCMVCUncertainty*,allocator<BCMVCUncertainty*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCUncertainty*,allocator<BCMVCUncertainty*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR = { "vector<BCMVCMeasurement*,allocator<BCMVCMeasurement*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCMeasurement*,allocator<BCMVCMeasurement*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR = { "vector<TVectorT<double>,allocator<TVectorT<double> > >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVectorT<double>,allocator<TVectorT<double> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR = { "vector<TMatrixT<double>,allocator<TMatrixT<double> > >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixT<double>,allocator<TMatrixT<double> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR = { "vector<BCMVCombination::NuisanceParameter,allocator<BCMVCombination::NuisanceParameter> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCombination::NuisanceParameter,allocator<BCMVCombination::NuisanceParameter> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR = { "vector<BCMVCObservable*,allocator<BCMVCObservable*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCObservable*,allocator<BCMVCObservable*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel = { "BCMVCPhysicsModel" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCMVCPhysicsModelDict() {
  G__BCMVCPhysicsModelDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_string.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_BCEngineMCMC.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_BCIntegrate.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_BCModel.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_BCMVCombination.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCMVCPhysicsModelDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_string);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_BCEngineMCMC);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_BCIntegrate);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_BCModel);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_BCMVCombination);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCMVCPhysicsModelDictLN_BCMVCPhysicsModel),sizeof(BCMVCPhysicsModel),-1,1280,(char*)NULL,G__setup_memvarBCMVCPhysicsModel,G__setup_memfuncBCMVCPhysicsModel);
}
extern "C" void G__cpp_setupBCMVCPhysicsModelDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCMVCPhysicsModelDict()");
  G__set_cpp_environmentBCMVCPhysicsModelDict();
  G__cpp_setup_tagtableBCMVCPhysicsModelDict();

  G__cpp_setup_inheritanceBCMVCPhysicsModelDict();

  G__cpp_setup_typetableBCMVCPhysicsModelDict();

  G__cpp_setup_memvarBCMVCPhysicsModelDict();

  G__cpp_setup_memfuncBCMVCPhysicsModelDict();
  G__cpp_setup_globalBCMVCPhysicsModelDict();
  G__cpp_setup_funcBCMVCPhysicsModelDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCMVCPhysicsModelDict();
  return;
}
class G__cpp_setup_initBCMVCPhysicsModelDict {
  public:
    G__cpp_setup_initBCMVCPhysicsModelDict() { G__add_setup_func("BCMVCPhysicsModelDict",(G__incsetup)(&G__cpp_setupBCMVCPhysicsModelDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCMVCPhysicsModelDict() { G__remove_setup_func("BCMVCPhysicsModelDict"); }
};
G__cpp_setup_initBCMVCPhysicsModelDict G__cpp_setup_initializerBCMVCPhysicsModelDict;

