/********************************************************************
* BCMVCUncertaintyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCMVCUncertaintyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCMVCUncertaintyDict();
extern void G__cpp_setup_inheritanceBCMVCUncertaintyDict();
extern void G__cpp_setup_typetableBCMVCUncertaintyDict();
extern void G__cpp_setup_memvarBCMVCUncertaintyDict();
extern void G__cpp_setup_globalBCMVCUncertaintyDict();
extern void G__cpp_setup_memfuncBCMVCUncertaintyDict();
extern void G__cpp_setup_funcBCMVCUncertaintyDict();
extern void G__set_cpp_environmentBCMVCUncertaintyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BCMVCUncertainty.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCMVCUncertaintyDictLN_string;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__BCMVCUncertaintyDictLN_BCMVCUncertainty;

/* STUB derived class for protected member access */
