//
// File generated by /app/cern/root_v5.34.38/bin/rootcint at Tue Feb 11 16:59:50 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCMVCombinationDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCMVCombinationDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void BCMVCombination_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCMVCombination_Dictionary();
   static void *new_BCMVCombination(void *p = 0);
   static void *newArray_BCMVCombination(Long_t size, void *p);
   static void delete_BCMVCombination(void *p);
   static void deleteArray_BCMVCombination(void *p);
   static void destruct_BCMVCombination(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::BCMVCombination*)
   {
      ::BCMVCombination *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCMVCombination),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCMVCombination", "./BCMVCombination.h", 27,
                  typeid(::BCMVCombination), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &BCMVCombination_Dictionary, isa_proxy, 0,
                  sizeof(::BCMVCombination) );
      instance.SetNew(&new_BCMVCombination);
      instance.SetNewArray(&newArray_BCMVCombination);
      instance.SetDelete(&delete_BCMVCombination);
      instance.SetDeleteArray(&deleteArray_BCMVCombination);
      instance.SetDestructor(&destruct_BCMVCombination);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::BCMVCombination*)
   {
      return GenerateInitInstanceLocal((::BCMVCombination*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCMVCombination*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCMVCombination_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::BCMVCombination*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_BCMVCombination(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCMVCombination : new ::BCMVCombination;
   }
   static void *newArray_BCMVCombination(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCMVCombination[nElements] : new ::BCMVCombination[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCMVCombination(void *p) {
      delete ((::BCMVCombination*)p);
   }
   static void deleteArray_BCMVCombination(void *p) {
      delete [] ((::BCMVCombination*)p);
   }
   static void destruct_BCMVCombination(void *p) {
      typedef ::BCMVCombination current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::BCMVCombination

/********************************************************
* BCMVCombinationDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCMVCombinationDict();

extern "C" void G__set_cpp_environmentBCMVCombinationDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BCMVCombination.h");
  G__cpp_reset_tagtableBCMVCombinationDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCMVCombinationDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCMVCombination */
static int G__BCMVCombinationDict_329_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCMVCombination* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCMVCombination[n];
     } else {
       p = new((void*) gvp) BCMVCombination[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCMVCombination;
     } else {
       p = new((void*) gvp) BCMVCombination;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->AddObservable(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->AddUncertainty(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->AddMeasurement(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, (double) G__double(libp->para[2]), *((vector<double>*) G__int(libp->para[3])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->GetNObservables());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->GetNUncertainties());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->GetNMeasurements());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->GetNActiveMeasurements());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCMVCombination*) G__getstructoffset())->GetUncertainty((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCMVCombination*) G__getstructoffset())->GetMeasurement((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TMatrixD* pobj;
         TMatrixD xobj = ((BCMVCombination*) G__getstructoffset())->GetCovarianceMatrix();
         pobj = new TMatrixD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TMatrixD* pobj;
         TMatrixD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUEWeights();
         pobj = new TMatrixD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVectorD* pobj;
         TVectorD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUECentralValues();
         pobj = new TVectorD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVectorD* pobj;
         TVectorD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUEUncertainties();
         pobj = new TVectorD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVectorD* pobj;
         TVectorD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUEUncertainties((int) G__int(libp->para[0]));
         pobj = new TVectorD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TMatrixD* pobj;
         TMatrixD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUECovarianceMatrix();
         pobj = new TMatrixD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TMatrixD* pobj;
         TMatrixD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUECovarianceMatrix((int) G__int(libp->para[0]));
         pobj = new TMatrixD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TMatrixD* pobj;
         TMatrixD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUECorrelationMatrix((int) G__int(libp->para[0]));
         pobj = new TMatrixD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TMatrixD* pobj;
         TMatrixD xobj = ((BCMVCombination*) G__getstructoffset())->GetBLUECorrelationMatrix();
         pobj = new TMatrixD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((BCMVCombination*) G__getstructoffset())->GetVectorObservable();
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVectorD* pobj;
         TVectorD xobj = ((BCMVCombination*) G__getstructoffset())->GetVectorMeasurements();
         pobj = new TVectorD(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->GetIndexMeasurement(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->GetIndexUncertainty(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->GetIndexObservable(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCMVCombination*) G__getstructoffset())->ReadInput(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->CalculateCorrelationMatrix((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCMVCombination*) G__getstructoffset())->CalculateCovarianceMatrix(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      ((BCMVCombination*) G__getstructoffset())->CalculateCovarianceMatrix();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->CalculateHelperVectors();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCMVCombination*) G__getstructoffset())->PositiveDefinite());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->CalculateBLUE();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->PrepareAnalysis();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCMVCombination*) G__getstructoffset())->PrintBLUEResults(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((BCMVCombination*) G__getstructoffset())->PrintMatrix(*(TMatrixT<double>*) libp->para[0].ref, *((string*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      ((BCMVCombination*) G__getstructoffset())->PrintMatrix(*(TMatrixT<double>*) libp->para[0].ref);
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCMVCombinationDict_329_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((BCMVCombination*) G__getstructoffset())->PrintVector(*(TVectorD*) libp->para[0].ref, *((string*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      ((BCMVCombination*) G__getstructoffset())->PrintVector(*(TVectorD*) libp->para[0].ref);
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BCMVCombinationDict_329_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BCMVCombination* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BCMVCombination(*(BCMVCombination*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCMVCombination G__TBCMVCombination;
static int G__BCMVCombinationDict_329_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCMVCombination*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCMVCombination*) (soff+(sizeof(BCMVCombination)*i)))->~G__TBCMVCombination();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCMVCombination*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCMVCombination*) (soff))->~G__TBCMVCombination();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BCMVCombinationDict_329_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCMVCombination* dest = (BCMVCombination*) G__getstructoffset();
   *dest = *(BCMVCombination*) libp->para[0].ref;
   const BCMVCombination& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCMVCombination */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCMVCombinationDict {
 public:
  G__Sizep2memfuncBCMVCombinationDict(): p(&G__Sizep2memfuncBCMVCombinationDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCMVCombinationDict::*p)();
};

size_t G__get_sizep2memfuncBCMVCombinationDict()
{
  G__Sizep2memfuncBCMVCombinationDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCMVCombinationDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination))) {
     BCMVCombination *G__Lderived;
     G__Lderived=(BCMVCombination*)0x1000;
     {
       BCModel *G__Lpbase=(BCModel*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination),G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCModel),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       BCIntegrate *G__Lpbase=(BCIntegrate*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination),G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCIntegrate),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       BCEngineMCMC *G__Lpbase=(BCEngineMCMC*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination),G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCEngineMCMC),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCMVCombinationDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCParameter*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<unsigned>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TTree*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<MCMCThreadLocalStorage>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCEngineMCMC::MCMCThreadLocalStorage>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2D*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCH1D*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCH2D*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TNamed*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCModel*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorD",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixD",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCUncertainty*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCMeasurement*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVectorD>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVectorT<double> >",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixD>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixT<double> >",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<NuisanceParameter>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCombination::NuisanceParameter>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCMVCObservable*>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCMVCombination */
static void G__setup_memvarBCMVCombination(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination));
   { BCMVCombination *p; p=(BCMVCombination*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR),G__defined_typename("vector<BCMVCUncertainty*>"),-1,2,"fUncertainties=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR),G__defined_typename("vector<BCMVCMeasurement*>"),-1,2,"fMeasurements=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR),G__defined_typename("TMatrixD"),-1,2,"fCovarianceMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR),G__defined_typename("TMatrixD"),-1,2,"fInvCovarianceMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fDetCovariance=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR),G__defined_typename("TVectorD"),-1,2,"fVectorMeasurements=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR),G__defined_typename("TVectorD"),-1,2,"fVectorActiveMeasurements=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fVectorObservable=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fVectorActiveObservable=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR),G__defined_typename("TMatrixD"),-1,2,"fBLUEWeights=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR),G__defined_typename("TVectorD"),-1,2,"fBLUECentral=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR),G__defined_typename("TVectorD"),-1,2,"fBLUEUncertainties=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR),G__defined_typename("vector<TVectorD>"),-1,2,"fBLUEUncertaintiesPerSource=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR),G__defined_typename("TMatrixD"),-1,2,"fBLUECovarianceMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),G__defined_typename("vector<TMatrixD>"),-1,2,"fBLUECovarianceMatrices=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),G__defined_typename("vector<TMatrixD>"),-1,2,"fBLUECorrelationMatrices=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR),G__defined_typename("TMatrixD"),-1,2,"fBLUECorrelationMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fNObservables=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fNNuisanceCorrelation=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR),G__defined_typename("vector<NuisanceParameter>"),-1,2,"fNuisanceCorrelation=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR),G__defined_typename("vector<BCMVCObservable*>"),-1,2,"fObservables=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCMVCombinationDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCMVCombination(void) {
   /* BCMVCombination */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination));
   G__memfunc_setup("BCMVCombination",1435,G__BCMVCombinationDict_329_0_1, 105, G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddObservable",1294,G__BCMVCombinationDict_329_0_2, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - name d - - 0 - min "
"d - - 0 - max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddUncertainty",1439,G__BCMVCombinationDict_329_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddMeasurement",1423,G__BCMVCombinationDict_329_0_4, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'string' - 0 - name u 'string' - 0 - observable "
"d - - 0 - value u 'vector<double,allocator<double> >' 'vector<double>' 0 - uncertainties", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNObservables",1510,G__BCMVCombinationDict_329_0_5, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNUncertainties",1740,G__BCMVCombinationDict_329_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNMeasurements",1639,G__BCMVCombinationDict_329_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNActiveMeasurements",2243,G__BCMVCombinationDict_329_0_8, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetUncertainty",1462,G__BCMVCombinationDict_329_0_9, 85, G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCUncertainty), -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMeasurement",1446,G__BCMVCombinationDict_329_0_10, 85, G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCMeasurement), -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCovarianceMatrix",1936,G__BCMVCombinationDict_329_0_11, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR), G__defined_typename("TMatrixD"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUEWeights",1315,G__BCMVCombinationDict_329_0_12, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR), G__defined_typename("TMatrixD"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUECentralValues",1921,G__BCMVCombinationDict_329_0_13, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR), G__defined_typename("TVectorD"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUEUncertainties",1958,G__BCMVCombinationDict_329_0_14, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR), G__defined_typename("TVectorD"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUEUncertainties",1958,G__BCMVCombinationDict_329_0_15, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR), G__defined_typename("TVectorD"), 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUECovarianceMatrix",2232,G__BCMVCombinationDict_329_0_16, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR), G__defined_typename("TMatrixD"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUECovarianceMatrix",2232,G__BCMVCombinationDict_329_0_17, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR), G__defined_typename("TMatrixD"), 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUECorrelationMatrix",2367,G__BCMVCombinationDict_329_0_18, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR), G__defined_typename("TMatrixD"), 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBLUECorrelationMatrix",2367,G__BCMVCombinationDict_329_0_19, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR), G__defined_typename("TMatrixD"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVectorObservable",1944,G__BCMVCombinationDict_329_0_20, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVectorMeasurements",2188,G__BCMVCombinationDict_329_0_21, 117, G__get_linked_tagnum(&G__BCMVCombinationDictLN_TVectorTlEdoublegR), G__defined_typename("TVectorD"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIndexMeasurement",1950,G__BCMVCombinationDict_329_0_22, 105, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - measurement u 'string' - 0 - observable", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIndexUncertainty",1966,G__BCMVCombinationDict_329_0_23, 105, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIndexObservable",1821,G__BCMVCombinationDict_329_0_24, 105, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadInput",908,G__BCMVCombinationDict_329_0_25, 105, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateCorrelationMatrix",2693,G__BCMVCombinationDict_329_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateCovarianceMatrix",2558,G__BCMVCombinationDict_329_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 'std::vector<double>(0)' nuisance", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateHelperVectors",2260,G__BCMVCombinationDict_329_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PositiveDefinite",1659,G__BCMVCombinationDict_329_0_29, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateBLUE",1206,G__BCMVCombinationDict_329_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrepareAnalysis",1555,G__BCMVCombinationDict_329_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintBLUEResults",1575,G__BCMVCombinationDict_329_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintMatrix",1154,G__BCMVCombinationDict_329_0_33, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMatrixT<double>' - 1 - matrix u 'string' - 0 '\"matrix\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintVector",1152,G__BCMVCombinationDict_329_0_34, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TVectorT<double>' 'TVectorD' 1 - vector u 'string' - 0 '\"vector\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LogLikelihood",1318,(G__InterfaceMethod) NULL,100, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("BCMVCombination", 1435, G__BCMVCombinationDict_329_0_36, (int) ('i'), G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination), -1, 0, 1, 1, 1, 0, "u 'BCMVCombination' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCMVCombination", 1561, G__BCMVCombinationDict_329_0_37, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BCMVCombinationDict_329_0_38, (int) ('u'), G__get_linked_tagnum(&G__BCMVCombinationDictLN_BCMVCombination), -1, 1, 1, 1, 1, 0, "u 'BCMVCombination' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCMVCombinationDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCMVCombinationDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCMVCombinationDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR = { "vector<BCParameter*,allocator<BCParameter*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCParameter*,allocator<BCParameter*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_BCEngineMCMC = { "BCEngineMCMC" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR = { "vector<TTree*,allocator<TTree*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TTree*,allocator<TTree*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR = { "vector<BCEngineMCMC::MCMCThreadLocalStorage,allocator<BCEngineMCMC::MCMCThreadLocalStorage> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCEngineMCMC::MCMCThreadLocalStorage,allocator<BCEngineMCMC::MCMCThreadLocalStorage> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR = { "vector<TH2D*,allocator<TH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2D*,allocator<TH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_BCIntegrate = { "BCIntegrate" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR = { "vector<BCH1D*,allocator<BCH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCH1D*,allocator<BCH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR = { "vector<BCH2D*,allocator<BCH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCH2D*,allocator<BCH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_BCModel = { "BCModel" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR = { "vector<TNamed*,allocator<TNamed*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TNamed*,allocator<TNamed*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR = { "vector<BCModel*,allocator<BCModel*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCModel*,allocator<BCModel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_BCMVCMeasurement = { "BCMVCMeasurement" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_BCMVCUncertainty = { "BCMVCUncertainty" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_BCMVCombination = { "BCMVCombination" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR = { "vector<BCMVCUncertainty*,allocator<BCMVCUncertainty*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCUncertainty*,allocator<BCMVCUncertainty*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR = { "vector<BCMVCMeasurement*,allocator<BCMVCMeasurement*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCMeasurement*,allocator<BCMVCMeasurement*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR = { "vector<TVectorT<double>,allocator<TVectorT<double> > >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVectorT<double>,allocator<TVectorT<double> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR = { "vector<TMatrixT<double>,allocator<TMatrixT<double> > >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixT<double>,allocator<TMatrixT<double> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR = { "vector<BCMVCombination::NuisanceParameter,allocator<BCMVCombination::NuisanceParameter> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCombination::NuisanceParameter,allocator<BCMVCombination::NuisanceParameter> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR = { "vector<BCMVCObservable*,allocator<BCMVCObservable*> >" , 99 , -1 };
G__linked_taginfo G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCMVCObservable*,allocator<BCMVCObservable*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCMVCombinationDict() {
  G__BCMVCombinationDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_string.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_BCEngineMCMC.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_BCIntegrate.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_BCModel.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__BCMVCombinationDictLN_BCMVCMeasurement.tagnum = -1 ;
  G__BCMVCombinationDictLN_BCMVCUncertainty.tagnum = -1 ;
  G__BCMVCombinationDictLN_BCMVCombination.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR.tagnum = -1 ;
  G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCMVCombinationDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_string);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_BCEngineMCMC);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCEngineMCMCcLcLMCMCThreadLocalStoragecOallocatorlEBCEngineMCMCcLcLMCMCThreadLocalStoragegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_BCIntegrate);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH1DmUcOallocatorlEBCH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCH2DmUcOallocatorlEBCH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_BCModel);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_BCMVCMeasurement);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_BCMVCUncertainty);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_BCMVCombination),sizeof(BCMVCombination),-1,1280,(char*)NULL,G__setup_memvarBCMVCombination,G__setup_memfuncBCMVCombination);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCUncertaintymUcOallocatorlEBCMVCUncertaintymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCMeasurementmUcOallocatorlEBCMVCMeasurementmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETVectorTlEdoublegRcOallocatorlETVectorTlEdoublegRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCombinationcLcLNuisanceParametercOallocatorlEBCMVCombinationcLcLNuisanceParametergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_vectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCMVCombinationDictLN_reverse_iteratorlEvectorlEBCMVCObservablemUcOallocatorlEBCMVCObservablemUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupBCMVCombinationDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCMVCombinationDict()");
  G__set_cpp_environmentBCMVCombinationDict();
  G__cpp_setup_tagtableBCMVCombinationDict();

  G__cpp_setup_inheritanceBCMVCombinationDict();

  G__cpp_setup_typetableBCMVCombinationDict();

  G__cpp_setup_memvarBCMVCombinationDict();

  G__cpp_setup_memfuncBCMVCombinationDict();
  G__cpp_setup_globalBCMVCombinationDict();
  G__cpp_setup_funcBCMVCombinationDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCMVCombinationDict();
  return;
}
class G__cpp_setup_initBCMVCombinationDict {
  public:
    G__cpp_setup_initBCMVCombinationDict() { G__add_setup_func("BCMVCombinationDict",(G__incsetup)(&G__cpp_setupBCMVCombinationDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCMVCombinationDict() { G__remove_setup_func("BCMVCombinationDict"); }
};
G__cpp_setup_initBCMVCombinationDict G__cpp_setup_initializerBCMVCombinationDict;

