//
// File generated by /app/cern/root_v5.34.38/bin/rootcint at Tue Feb 11 16:57:02 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCParameterSetDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCParameterSetDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void BCParameterSet_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCParameterSet_Dictionary();
   static void *new_BCParameterSet(void *p = 0);
   static void *newArray_BCParameterSet(Long_t size, void *p);
   static void delete_BCParameterSet(void *p);
   static void deleteArray_BCParameterSet(void *p);
   static void destruct_BCParameterSet(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::BCParameterSet*)
   {
      ::BCParameterSet *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCParameterSet),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCParameterSet", "./../BAT/BCParameterSet.h", 29,
                  typeid(::BCParameterSet), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &BCParameterSet_Dictionary, isa_proxy, 0,
                  sizeof(::BCParameterSet) );
      instance.SetNew(&new_BCParameterSet);
      instance.SetNewArray(&newArray_BCParameterSet);
      instance.SetDelete(&delete_BCParameterSet);
      instance.SetDeleteArray(&deleteArray_BCParameterSet);
      instance.SetDestructor(&destruct_BCParameterSet);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::BCParameterSet*)
   {
      return GenerateInitInstanceLocal((::BCParameterSet*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCParameterSet*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCParameterSet_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::BCParameterSet*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_BCParameterSet(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCParameterSet : new ::BCParameterSet;
   }
   static void *newArray_BCParameterSet(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCParameterSet[nElements] : new ::BCParameterSet[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCParameterSet(void *p) {
      delete ((::BCParameterSet*)p);
   }
   static void deleteArray_BCParameterSet(void *p) {
      delete [] ((::BCParameterSet*)p);
   }
   static void destruct_BCParameterSet(void *p) {
      typedef ::BCParameterSet current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::BCParameterSet

/********************************************************
* BCParameterSetDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCParameterSetDict();

extern "C" void G__set_cpp_environmentBCParameterSetDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../BAT/BCParameterSet.h");
  G__cpp_reset_tagtableBCParameterSetDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCParameterSetDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCParameterSet */
static int G__BCParameterSetDict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCParameterSet*) G__getstructoffset())->Add((BCParameter*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCParameterSetDict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCParameterSet*) G__getstructoffset())->Clear((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCParameterSetDict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const BCParameterSet*) G__getstructoffset())->operator[]((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCParameterSetDict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const BCParameterSet*) G__getstructoffset())->Get((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCParameterSetDict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const BCParameterSet*) G__getstructoffset())->Get(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCParameterSetDict_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const BCParameterSet*) G__getstructoffset())->Index(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCParameterSetDict_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const BCParameterSet*) G__getstructoffset())->Size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCParameterSetDict_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 103, (long) ((const BCParameterSet*) G__getstructoffset())->ValidIndex((unsigned int) G__int(libp->para[0]), *((const string*) G__int(libp->para[1]))));
      break;
   case 1:
      G__letint(result7, 103, (long) ((const BCParameterSet*) G__getstructoffset())->ValidIndex((unsigned int) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic default constructor
static int G__BCParameterSetDict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCParameterSet *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCParameterSet[n];
     } else {
       p = new((void*) gvp) BCParameterSet[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCParameterSet;
     } else {
       p = new((void*) gvp) BCParameterSet;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameterSet));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BCParameterSetDict_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BCParameterSet* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BCParameterSet(*(BCParameterSet*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameterSet));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCParameterSet G__TBCParameterSet;
static int G__BCParameterSetDict_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCParameterSet*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCParameterSet*) (soff+(sizeof(BCParameterSet)*i)))->~G__TBCParameterSet();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCParameterSet*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCParameterSet*) (soff))->~G__TBCParameterSet();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BCParameterSetDict_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCParameterSet* dest = (BCParameterSet*) G__getstructoffset();
   *dest = *(BCParameterSet*) libp->para[0].ref;
   const BCParameterSet& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCParameterSet */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCParameterSetDict {
 public:
  G__Sizep2memfuncBCParameterSetDict(): p(&G__Sizep2memfuncBCParameterSetDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCParameterSetDict::*p)();
};

size_t G__get_sizep2memfuncBCParameterSetDict()
{
  G__Sizep2memfuncBCParameterSetDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCParameterSetDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCParameterSetDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCParameter*>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCParameterSet */
static void G__setup_memvarBCParameterSet(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameterSet));
   { BCParameterSet *p; p=(BCParameterSet*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR),G__defined_typename("vector<BCParameter*>"),-1,4,"fPars=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCParameterSetDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCParameterSet(void) {
   /* BCParameterSet */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameterSet));
   G__memfunc_setup("Add",265,G__BCParameterSetDict_169_0_1, 103, -1, -1, 0, 1, 1, 1, 0, "U 'BCParameter' - 0 - par", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__BCParameterSetDict_169_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__BCParameterSetDict_169_0_3, 85, G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameter), -1, 0, 1, 1, 1, 8, "h - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Get",288,G__BCParameterSetDict_169_0_4, 85, G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameter), -1, 0, 1, 1, 1, 8, "h - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Get",288,G__BCParameterSetDict_169_0_5, 85, G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameter), -1, 0, 1, 1, 1, 8, "u 'string' - 11 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Index",504,G__BCParameterSetDict_169_0_6, 104, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Size",411,G__BCParameterSetDict_169_0_7, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ValidIndex",1000,G__BCParameterSetDict_169_0_8, 103, -1, -1, 0, 2, 1, 1, 8, 
"h - - 0 - - u 'string' - 10 '\"CheckIndex\"' caller", (char*)NULL, (void*) NULL, 0);
   // automatic default constructor
   G__memfunc_setup("BCParameterSet", 1362, G__BCParameterSetDict_169_0_9, (int) ('i'), G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameterSet), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BCParameterSet", 1362, G__BCParameterSetDict_169_0_10, (int) ('i'), G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameterSet), -1, 0, 1, 1, 1, 0, "u 'BCParameterSet' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCParameterSet", 1488, G__BCParameterSetDict_169_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BCParameterSetDict_169_0_12, (int) ('u'), G__get_linked_tagnum(&G__BCParameterSetDictLN_BCParameterSet), -1, 1, 1, 1, 1, 0, "u 'BCParameterSet' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCParameterSetDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCParameterSetDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCParameterSetDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCParameterSetDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_BCParameter = { "BCParameter" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_BCParameterSet = { "BCParameterSet" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR = { "vector<BCParameter*,allocator<BCParameter*> >" , 99 , -1 };
G__linked_taginfo G__BCParameterSetDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCParameter*,allocator<BCParameter*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCParameterSetDict() {
  G__BCParameterSetDictLN_string.tagnum = -1 ;
  G__BCParameterSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCParameterSetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCParameterSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCParameterSetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCParameterSetDictLN_BCParameter.tagnum = -1 ;
  G__BCParameterSetDictLN_BCParameterSet.tagnum = -1 ;
  G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR.tagnum = -1 ;
  G__BCParameterSetDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCParameterSetDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_string);
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_BCParameter);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_BCParameterSet),sizeof(BCParameterSet),-1,0,(char*)NULL,G__setup_memvarBCParameterSet,G__setup_memfuncBCParameterSet);
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCParameterSetDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupBCParameterSetDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCParameterSetDict()");
  G__set_cpp_environmentBCParameterSetDict();
  G__cpp_setup_tagtableBCParameterSetDict();

  G__cpp_setup_inheritanceBCParameterSetDict();

  G__cpp_setup_typetableBCParameterSetDict();

  G__cpp_setup_memvarBCParameterSetDict();

  G__cpp_setup_memfuncBCParameterSetDict();
  G__cpp_setup_globalBCParameterSetDict();
  G__cpp_setup_funcBCParameterSetDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCParameterSetDict();
  return;
}
class G__cpp_setup_initBCParameterSetDict {
  public:
    G__cpp_setup_initBCParameterSetDict() { G__add_setup_func("BCParameterSetDict",(G__incsetup)(&G__cpp_setupBCParameterSetDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCParameterSetDict() { G__remove_setup_func("BCParameterSetDict"); }
};
G__cpp_setup_initBCParameterSetDict G__cpp_setup_initializerBCParameterSetDict;

