/********************************************************************
* BCParameterSetDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCParameterSetDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCParameterSetDict();
extern void G__cpp_setup_inheritanceBCParameterSetDict();
extern void G__cpp_setup_typetableBCParameterSetDict();
extern void G__cpp_setup_memvarBCParameterSetDict();
extern void G__cpp_setup_globalBCParameterSetDict();
extern void G__cpp_setup_memfuncBCParameterSetDict();
extern void G__cpp_setup_funcBCParameterSetDict();
extern void G__set_cpp_environmentBCParameterSetDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../BAT/BCParameterSet.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCParameterSetDictLN_string;
extern G__linked_taginfo G__BCParameterSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCParameterSetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCParameterSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCParameterSetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCParameterSetDictLN_BCParameter;
extern G__linked_taginfo G__BCParameterSetDictLN_BCParameterSet;
extern G__linked_taginfo G__BCParameterSetDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR;
extern G__linked_taginfo G__BCParameterSetDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
