gatordir="/disk/bulk_atp/gator"
binary="/disk/bulk_atp/gator/simulations/gator_v2.0/bin/Linux-g++/gator_1.2"
datadir="/disk/bulk_atp/gator/Sample_Sim_and_Analysis_Results"
sample="Tetratex_veryhighdens"
queue="5:00:00"
maxnodes=100
totevents= 10000000
n_beamOn= 100000
isotope_list=[ "232Th"]
