#/control/verbose 0
#/run/verbose 0
#/event/verbose 0
#/tracking/verbose 0

/vis/scene/create
#/vis/open OGLIX
/vis/open VRML2FILE
#/vis/drawVolume Holder1_phys
#/vis/geometry/set/visibility cavity1_log ! false
/vis/viewer/set/style surface
/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/viewpointVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 45 120 deg

#/vis/viewer/zoom 1.0
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
